### ISSUE TITLE
Add the rule to warn about skipped heading levels

### ISSUE THREAD

**Issue by YusukeHirao** [markuplint/markuplint#1151] opened 2023-09-18 06:33 UTC
Rel: https://github.com/whatwg/html/issues/8366

Correct:
```html
<h1>A</h1>
<h2>B</h2>
<h3>C</h3>
```

Incorrect:
```html
<h1>A</h1>
<h3>B</h3><!-- skipped heading levels -->
<h2>C</h2>
```

**Comment by kagankan** [comment] 2023-10-29 06:24
Probably a duplicate of #695

**Closed** 2023-12-25 09:03 UTC
Labels: duplicate, Features: Required, Rule
